### ISSUE TITLE
Detailed training environment for help

### ISSUE THREAD

**Issue by shanyang0509** [hpi-xnor/BNext#3]
hello, could you offer me the detailed training environment? I accoured the problems in this environment and use the docker:
Package                Version
---------------------- -------------------
backcall               0.2.0
beautifulsoup4         4.9.3
brotlipy               0.7.0
certifi                2020.12.5
cffi                   1.14.3
chardet                3.0.4
conda                  4.9.2
conda-build            3.21.4
conda-package-handling 1.7.2
cryptography           3.2.1
decorator              4.4.2
dnspython              2.1.0
einops                 0.6.0
filelock               3.0.12
glob2                  0.7
huggingface-hub        0.11.1
idna                   2.10
ipython                7.21.0
ipython-genutils       0.2.0
jedi                   0.17.0
Jinja2                 2.11.3
libarchive-c           2.9
MarkupSafe             1.1.1
mkl-fft                1.3.0
mkl-random             1.1.1
mkl-service            2.3.0
mysqlclient            2.1.1
numpy                  1.19.2
nvidia-dali-cuda110    1.20.0
olefile                0.46
packaging              22.0
parso                  0.8.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.1.1
pip                    20.2.4
pkginfo                1.7.0
prompt-toolkit         3.0.8
psutil                 5.8.0
ptyprocess             0.7.0
pycosat                0.6.3
pycparser              2.20
Pygments               2.8.0
pyOpenSSL              19.1.0
PySocks                1.7.1
python-etcd            0.4.5
pytorch-ranger         0.1.1
pytorch-warmup         0.1.1
pytz                   2021.1
PyYAML                 5.4.1
requests               2.24.0
ruamel-yaml            0.15.87
setuptools             50.3.1.post20201107
six                    1.15.0
soupsieve              2.2
timm                   0.6.12
torch                  1.8.0
torch-optimizer        0.3.0
torchelastic           0.2.2
torchinfo              1.7.1
torchtext              0.9.0
torchvision            0.9.0
tqdm                   4.51.0
traitlets              5.0.5
typing-extensions      3.7.4.3
urllib3                1.25.11
wcwidth                0.2.5
wheel                  0.35.1

I occured the problem is:
Traceback (most recent call last):
  File "train_assistant_group_amp_fune2.py", line 919, in <module>
    main()
  File "train_assistant_group_amp_fune2.py", line 912, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/workspace/BNext/src/train_assistant_group_amp_fune2.py", line 272, in main_worker
    assistant_teachers.append(models.efficientnet_b0(pretrained=True))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Sequential' object has no attribute 'append'

**Comment by NicoNico6** [comment]
Hi, I have made a python environment file requirements.txt in the repository, you can build your version with the help of this
